spring.application.name=NotesApp
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/notes_app
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret=mySecretKeyForJWTTokenGeneration
jwt.expiration=3600

# Rate Limiting Configuration
rate-limit.login.capacity=5
rate-limit.login.refill-tokens=5
rate-limit.login.refill-minutes=1